!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 1000000
  - - ent_coef
    - auto
  - - gamma
    - 0.99
  - - gradient_steps
    - 1
  - - learning_rate
    - 0.0003
  - - learning_starts
    - 100
  - - n_timesteps
    - 300000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-3, net_arch=[256, 256])
  - - tau
    - 0.005
  - - train_freq
    - 1
  - - use_sde
    - false
